.PHONY: clean All

All:
	@echo "----------Building project:[ Norm_2 - Debug ]----------"
	@cd "Norm_2" && "$(MAKE)" -f  "Norm_2.mk"
clean:
	@echo "----------Cleaning project:[ Norm_2 - Debug ]----------"
	@cd "Norm_2" && "$(MAKE)" -f  "Norm_2.mk" clean
