.PHONY: clean All

All:
	@echo "----------Building project:[ project_4 - Debug ]----------"
	@cd "project_4" && "$(MAKE)" -f  "project_4.mk"
clean:
	@echo "----------Cleaning project:[ project_4 - Debug ]----------"
	@cd "project_4" && "$(MAKE)" -f  "project_4.mk" clean
