.PHONY: clean All

All:
	@echo "----------Building project:[ class_String - Debug ]----------"
	@cd "class_String" && "$(MAKE)" -f  "class_String.mk"
clean:
	@echo "----------Cleaning project:[ class_String - Debug ]----------"
	@cd "class_String" && "$(MAKE)" -f  "class_String.mk" clean
